package com.rr.client.core

import com.google.gson.JsonObject
import com.google.gson.JsonParser
import com.rr.client.core.model.ProtocolType
import com.rr.client.core.model.ProxyNode
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Test

/** Generic service fixtures only; no personal installed-app inventory is shipped. */
class PersonalServicesRoutingConfigTest {
    private fun config(smart: Boolean = true): JsonObject {
        val node = ProxyNode("test", "test", ProtocolType.SOCKS, "192.0.2.1", 1080,
            rawJson = """{"type":"socks","server":"192.0.2.1","server_port":1080}""")
        return JsonParser.parseString(ConfigBuilder.buildSingBoxConfig(
            selectedNode = node, allNodes = listOf(node), appRoutes = emptyList(), smartRouting = smart
        )).asJsonObject
    }

    private fun decision(root: JsonObject, section: String, host: String): String {
        val group = root.getAsJsonObject(section)
        val key = if (section == "dns") "server" else "outbound"
        return group.getAsJsonArray("rules").map { it.asJsonObject }.firstOrNull { rule ->
            rule.has(key) && (rule.getAsJsonArray("domain")?.any { it.asString == host } == true ||
                rule.getAsJsonArray("domain_suffix")?.any {
                    host == it.asString || host.endsWith("." + it.asString)
                } == true)
        }?.get(key)?.asString ?: group.get("final").asString
    }

    @Test
    fun domesticServicesUseLocalDnsAndDirectEvenWithoutDownloadedRules() {
        val root = config()
        listOf(
            "chat.deepseek.com", "api.deepseeksvc.com", "www.doubao.com", "p.doubaocdn.com",
            "www.qishui.com", "api.fqnovel.com", "p3-novel.byteimg.com", "www.fanqienovel.com",
            "www.kugou.com", "img.kgimg.com", "mybank.icbc.com.cn", "www.95588.com",
            "mobile.ccb.com", "ebsnew.boc.cn", "m.ecitic.com", "www.citicbank.com",
            "www.gdnybank.com", "app.10086.cn", "www.cmpassport.com", "tyrz.gd.gov.cn",
            "open.tp-link.com.cn", "account.xiaomi.com", "cn-ha.mqtt.io.mi.com", "ha.api.io.mi.com",
            "www.qqgameapp.com", "www.wegame.com"
        ).forEach { host ->
            assertEquals(host, "direct", decision(root, "route", host))
            assertEquals(host, "dns-direct", decision(root, "dns", host))
        }
    }

    @Test
    fun internationalSocialDeveloperAndGamingServicesUseProxyDnsTogether() {
        val root = config()
        listOf(
            "graph.facebook.com", "media.fbcdn.net", "i.instagram.com", "s.cdninstagram.com",
            "web.whatsapp.com", "media.whatsapp.net", "www.threads.com", "www.threads.net",
            "www.reddit.com", "v.redd.it", "i.redditmedia.com", "api.github.com",
            "raw.githubusercontent.com", "github-production-release-asset-2e65be.s3.amazonaws.com",
            "grok.com", "api.x.ai", "api.vk.com", "video.vkuservideo.net", "store.steampowered.com",
            "steamcommunity.com", "steammobile.akamaized.net", "coze.com"
        ).forEach { host ->
            assertEquals(host, "proxy", decision(root, "route", host))
            assertEquals(host, "dns-remote", decision(root, "dns", host))
        }
    }

    @Test
    fun sharedCloudAndRegionalHomeDevicesAreNotGuessedFromTheAppName() {
        val root = config()
        listOf(
            "unknown.roborock.com", "eu-ha.mqtt.io.mi.com", "us.tplinkcloud.com",
            "tenant.huaweicloud.com", "tenant.aliyuncs.com", "tenant.amazonaws.com",
            "evilgdnybank.com", "deepseek.com.example.org", "p3-novel.byteimg.com.example.org"
        ).forEach { host -> assertEquals(host, "proxy", decision(root, "route", host)) }
        val rules = root.getAsJsonObject("route").getAsJsonArray("rules")
        // No installed-app package names are generated by these service supplements.
        assertFalse(rules.any { it.asJsonObject.has("package_name") && it.asJsonObject.get("outbound")?.asString == "direct" })
    }

    @Test
    fun smartOffStillSendsDomesticServicesToProxy() {
        val root = config(smart = false)
        listOf("chat.deepseek.com", "www.gdnybank.com", "account.xiaomi.com").forEach { host ->
            assertEquals("proxy", decision(root, "route", host))
            assertEquals("dns-remote", decision(root, "dns", host))
        }
    }
}
